#!/bin/sh

# diy_part.sh中的UCI设置
[[ -f /etc/default_uci ]] && chmod +x /etc/default_uci && source /etc/default_uci
/etc/init.d/network restart

# 去除coremark定时任务
if [[ `grep -c "coremark" /etc/crontabs/root` -eq 1 ]]; then
  sed -i /coremark/d /etc/crontabs/root
fi

if [[ -f "/usr/lib/lua/luci/controller/ttyd.lua" ]]; then
	sed -i 's?services?system?g' "/usr/lib/lua/luci/controller/ttyd.lua"
fi

# chmod 0777 /etc/opkg/distfeeds.conf
if [[ `grep -c "pkgroacn" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/pkgroacn/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "helloworld" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/helloworld/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "ssrplus" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/ssrplus/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "passwall" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/passwall/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "OpenClash" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/OpenClash/d' /etc/opkg/distfeeds.conf
fi

luci_web=/usr/lib/lua/luci/view/admin_status/index.htm
if [[ -f "/etc/index.htm" ]]; then
	sed -i 's#localtime  = .*#localtime  = os.date("%Y-%m-%d") .. " " .. os.date("%X") .. " " .. translate(os.date("%A")),#g' "/etc/index.htm"
elif [[ -f "${luci_web}" ]]; then
	sed -i 's#localtime  = .*#localtime  = os.date("%Y-%m-%d") .. " " .. os.date("%X") .. " " .. translate(os.date("%A")),#g' "${luci_web}"
fi

if [[ -f "/etc/index.htm" ]] && [[ `grep -c "(<%=pcdata(ver.luciversion)%>)" "/etc/index.htm"` -eq '1' ]]; then
	sed -i 's?(<%=pcdata(ver.luciversion)%>)?- <%=pcdata(ver.luciversion)%>?g' "/etc/index.htm"
elif [[ `grep -c "(<%=pcdata(ver.luciversion)%>)" "${luci_web}"` -eq '1' ]]; then
	sed -i 's?(<%=pcdata(ver.luciversion)%>)?- <%=pcdata(ver.luciversion)%>?g' "${luci_web}"
fi

sed -i 's?=== WARNING! =====================================?=================== WARNING! ====================?g' /etc/profile

if [[ -n "$(grep "downloads.openwrt.org" /etc/opkg/distfeeds.conf)" ]]; then
	sed -i 's?downloads.openwrt.org?mirrors.cloud.tencent.com/openwrt?g' /etc/opkg/distfeeds.conf
fi

